# Generated by Django 2.2 on 2019-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="code",
            field=models.CharField(
                choices=[
                    ("R", "RED"),
                    ("G", "GREEN"),
                    ("B", "BLUE"),
                    ("O", "ORANGE"),
                    ("P", "PURPLE"),
                    ("Y", "YELLOW"),
                ],
                default=["R", "G", "B", "P"],
                max_length=4,
            ),
        ),
    ]
