# Generated by Django 2.2 on 2019-04-09 13:44

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_game_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="code",
            field=models.CharField(
                choices=[
                    ("R", "RED"),
                    ("G", "GREEN"),
                    ("B", "BLUE"),
                    ("O", "ORANGE"),
                    ("P", "PURPLE"),
                    ("Y", "YELLOW"),
                ],
                default=board.models.create_code,
                max_length=4,
            ),
        ),
    ]
