# Generated by Django 2.2 on 2019-04-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_auto_20190409_1344"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ("created",)},
        ),
    ]
