# Generated by Django 2.2 on 2019-04-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_movement"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="game",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="board.Game",
            ),
            preserve_default=False,
        ),
    ]
