# Generated by Django 2.2 on 2019-04-10 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0007_movement_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="player",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
