version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations --settings=config.settings && python manage.py migrate --settings=config.settings && python manage.py runserver 0.0.0.0:8000 --settings=config.settings"
    container_name: mastermindAPI
    volumes:
      - .:/mastermindAPI
    ports:
      - "8000:8000"
    depends_on:
      -  db
  db:
    image: nouchka/sqlite3